// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://soegyddtbyslyadtenaz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNvZWd5ZGR0YnlzbHlhZHRlbmF6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgyODIzMzAsImV4cCI6MjA2Mzg1ODMzMH0.33qfzBboRFf8X2JM2Xs6lG0VYQV3Kvt_f87bxAbVdas";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);